CREATE DATABASE Actividad

USE [Actividad]

CREATE TABLE Carreras(
	ID VARCHAR(4) NOT NULL PRIMARY KEY,
	Nombre VARCHAR(100) NOT NULL,
	FechaCreacion DATE NOT NULL CHECK(FechaCreacion < GETDATE()),
	Mail VARCHAR(100) NOT NULL UNIQUE,
	Nivel VARCHAR(20) NOT NULL CHECK(Nivel = 'Diplomatura' OR Nivel = 'Pregrado' OR Nivel = 'Grado' OR Nivel = 'Posgrado'),
	)

CREATE TABLE Alumnos (
	Legajo SMALLINT NOT NULL PRIMARY KEY IDENTITY(1000, 1),
	IDCarrera VARCHAR(4) NOT NULL FOREIGN KEY REFERENCES Carreras(ID),
	Apellidos VARCHAR(100) NOT NULL,
	Nombres VARCHAR(100) NOT NULL,
	FechaNac DATE NOT NULL CHECK(FechaNac < GETDATE()),
	Mail VARCHAR(100) NOT NULL UNIQUE,
	Telefono VARCHAR(20) NULL
)

CREATE TABLE Materias (
	ID SMALLINT NOT NULL PRIMARY KEY IDENTITY(1000, 1),
	IDCarrera VARCHAR(4) NOT NULL FOREIGN KEY REFERENCES Carreras(ID),
	Nombre varchar(100) NOT NULL,
	CargaHoraria INT NOT NULL CHECK(CargaHoraria > 0)
);